# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/exide/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Users/exide/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/exide/visualdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/exide/visualdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.8/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/exide/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/exide/visualdb/CMakeFiles /Users/exide/visualdb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/exide/visualdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named visualdb

# Build rule for target.
visualdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualdb
.PHONY : visualdb

# fast build rule for target.
visualdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/build
.PHONY : visualdb/fast

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/render.o: src/render.cpp.o
.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/shape.o: src/shape.cpp.o
.PHONY : src/shape.o

# target to build an object file
src/shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/shape.cpp.o
.PHONY : src/shape.cpp.o

src/shape.i: src/shape.cpp.i
.PHONY : src/shape.i

# target to preprocess a source file
src/shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/shape.cpp.i
.PHONY : src/shape.cpp.i

src/shape.s: src/shape.cpp.s
.PHONY : src/shape.s

# target to generate assembly for a file
src/shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/shape.cpp.s
.PHONY : src/shape.cpp.s

src/update.o: src/update.cpp.o
.PHONY : src/update.o

# target to build an object file
src/update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/update.cpp.o
.PHONY : src/update.cpp.o

src/update.i: src/update.cpp.i
.PHONY : src/update.i

# target to preprocess a source file
src/update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/update.cpp.i
.PHONY : src/update.cpp.i

src/update.s: src/update.cpp.s
.PHONY : src/update.s

# target to generate assembly for a file
src/update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/update.cpp.s
.PHONY : src/update.cpp.s

src/visualdb.o: src/visualdb.cpp.o
.PHONY : src/visualdb.o

# target to build an object file
src/visualdb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/visualdb.cpp.o
.PHONY : src/visualdb.cpp.o

src/visualdb.i: src/visualdb.cpp.i
.PHONY : src/visualdb.i

# target to preprocess a source file
src/visualdb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/visualdb.cpp.i
.PHONY : src/visualdb.cpp.i

src/visualdb.s: src/visualdb.cpp.s
.PHONY : src/visualdb.s

# target to generate assembly for a file
src/visualdb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualdb.dir/build.make CMakeFiles/visualdb.dir/src/visualdb.cpp.s
.PHONY : src/visualdb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... visualdb"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/shape.o"
	@echo "... src/shape.i"
	@echo "... src/shape.s"
	@echo "... src/update.o"
	@echo "... src/update.i"
	@echo "... src/update.s"
	@echo "... src/visualdb.o"
	@echo "... src/visualdb.i"
	@echo "... src/visualdb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

